practiced with recurtion and functions, finished homework
iwanttosmile4u/prjctr_homeworks pull request #3
Opened 2024-11-18 20:20 UTC by iwanttosmile4u

2024-11-19 20:13 UTC, myroslav-kolomiiets requested changes

2024-11-19 20:13 UTC, myroslav-kolomiiets commented on hw_3/index.js
> +  let validatedNumber = number;
`validatedNumber` лишня змінна, можна обійтись без її створення, лише `number`

2024-11-19 20:13 UTC, myroslav-kolomiiets commented on hw_3/index.js
> +  const isNumberCorrect = typeof number === 'number' && !isNaN(number) && number >= 0;
Це продубльовано на 29 рядку, відповідно можна винести в одну окрему функцію

2024-11-19 20:13 UTC, myroslav-kolomiiets commented on hw_3/index.js
> +    if (i % 2 !== 0) {
Можна обійтись без цієї умови, якщо переписати інакше крок ітерації на 35 рядку, це зробить код простіше і швидше, рекомендую подумати як

2024-11-21 14:00 UTC, iwanttosmile4u commented on hw_3/index.js
> +  let validatedNumber = number;
У цьому випадку вирішила зберегти number у змінній ```validatedNumber```, щоб не змінювати вхідний параметр функції.

2024-11-21 14:12 UTC, iwanttosmile4u commented on hw_3/index.js
> +    if (i % 2 !== 0) {
Реально. Дякую, перероблю!

2024-11-22 18:49 UTC, myroslav-kolomiiets approved these changes

2024-11-28 19:15 UTC, merged